name: PhantomBotDE CI/CD
on:
  release:
    types: [published]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dev
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_USER }}/phantombotde
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
